name: test-and-build-dev-pkg

on:
  pull_request:
    branches:
      - master

jobs:
  test_and_build_dev_pkg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "RUNNING TESTS"

      - name: Build
        run: echo "BUILDING"

      - name: Find if there was a version comment already
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: Package built

      - name: Create a comment with the built version id
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            New development package `0.16.0-dev${{ github.run_number }}` was successfuly built. To install, run:

            ```
            npm install @flutter-global/ppb-cdk-library@0.16.0-dev${{ github.run_number }}
            ```
